// supabase/functions/linkedin-generate/index.ts
// Portfolio Generator — LinkedIn Presence Generator
// Receives GitHub data + language → calls Groq → returns LinkedIn content

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

// ─── Types ────────────────────────────────────────────────────────────────────

interface RepoData {
  name: string;
  description: string | null;
  html_url: string;
  stars: number;
  language: string | null;
  topics: string[];
  readme: string | null;
  priority_score: number;
  pushed_at: string;
  fork: boolean;
  archived: boolean;
}

interface GitHubUser {
  login: string;
  name: string | null;
  bio: string | null;
  followers: number;
  following: number;
  public_repos: number;
  company: string | null;
  location: string | null;
  blog: string | null;
  created_at: string;
}

interface LinkedInRequest {
  githubData: {
    user: GitHubUser;
    top_repos: RepoData[];
    all_repos: RepoData[];
    languages: { language: string; bytes: number; percentage: number }[];
    total_stars: number;
    total_repos: number;
  };
  lang: "ar" | "en";
  generationId?: string;
}

interface ScoreBreakdown {
  readme_quality: number;
  commit_frequency: number;
  repo_descriptions: number;
  project_diversity: number;
  profile_completeness: number;
}

interface ProjectPost {
  repo_name: string;
  post_content: string;
}

interface LinkedInResponse {
  score: number;
  score_breakdown: ScoreBreakdown;
  weak_points: string[];
  headline: string;
  about: string;
  posts: ProjectPost[];
}

// ─── CORS Headers ────────────────────────────────────────────────────────────

const ALLOWED_ORIGINS = [
  "https://portfolio-generator-taupe.vercel.app",
];

function getCorsHeaders(requestOrigin: string | null): Record<string, string> {
  const origin =
    requestOrigin && ALLOWED_ORIGINS.includes(requestOrigin)
      ? requestOrigin
      : ALLOWED_ORIGINS[0];

  return {
    "Access-Control-Allow-Origin": origin,
    "Access-Control-Allow-Headers":
      "authorization, x-client-info, apikey, content-type",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Vary": "Origin",
  };
}

// ─── Helper: Update generation status ────────────────────────────────────────

async function updateGenerationStatus(
  supabase: ReturnType<typeof createClient>,
  generationId: string,
  status: "pending" | "processing" | "completed" | "failed",
  extra: Record<string, unknown> = {}
) {
  if (!generationId) return;
  await supabase
    .from("ai_generations")
    .update({ status, updated_at: new Date().toISOString(), ...extra })
    .eq("id", generationId);
}

// ─── Helper: Build Prompt ─────────────────────────────────────────────────────

function buildPrompt(req: LinkedInRequest): { system: string; user: string } {
  const { user, top_repos, languages, total_stars, total_repos } = req.githubData;
  const lang = req.lang || "en";
  const isArabic = lang === "ar";
  const fullName = user.name || user.login;

  // Top languages
  const topLangs = (languages || []).slice(0, 8).map((l) => l.language);

  // Account age in years
  const accountAge = user.created_at
    ? Math.floor(
        (Date.now() - new Date(user.created_at).getTime()) /
          (365.25 * 24 * 3600 * 1000)
      )
    : 1;

  // Repos with descriptions
  const reposWithDesc = (top_repos || []).filter((r) => r.description && r.description.trim().length > 10);
  const reposWithReadme = (top_repos || []).filter((r) => r.readme && r.readme.length > 100);

  // Recent activity (repos pushed in last 90 days)
  const ninetyDaysAgo = Date.now() - 90 * 24 * 3600 * 1000;
  const recentlyActive = (top_repos || []).filter(
    (r) => r.pushed_at && new Date(r.pushed_at).getTime() > ninetyDaysAgo
  );

  // Prepare repo summaries for prompt
  const repoSummaries = (top_repos || []).slice(0, 6).map((r) => ({
    name: r.name,
    description: r.description || "",
    language: r.language || "",
    stars: r.stars || 0,
    topics: (r.topics || []).slice(0, 5),
    readme_snippet: r.readme
      ? r.readme.slice(0, 400).replace(/\n+/g, " ").trim()
      : "",
    url: r.html_url || `https://github.com/${user.login}/${r.name}`,
  }));

  const viralTag = isArabic
    ? `\n\n🔗 Generated by DevPresence · portfolio-generator-taupe.vercel.app/linkedin.html`
    : `\n\n🔗 Generated by DevPresence · portfolio-generator-taupe.vercel.app/linkedin.html`;

  const systemAr = `أنت خبير في بناء الحضور المهني على LinkedIn للمطورين.
مهمتك: تحليل بيانات GitHub وإنشاء محتوى LinkedIn احترافي وجذاب.
اكتب بالعربية الفصحى الواضحة، مع الحفاظ على المصطلحات التقنية بالإنجليزية.
IMPORTANT: أجب دائماً بـ JSON صالح فقط — بدون markdown أو backticks أو مقدمة.`;

  const systemEn = `You are an expert LinkedIn personal brand strategist for software developers.
Your job: analyze GitHub data and generate compelling, authentic LinkedIn content.
Be specific, data-driven, and professional. Avoid generic phrases.
IMPORTANT: Always respond with valid JSON only — no markdown, no backticks, no preamble.`;

  const promptAr = `بناءً على بيانات GitHub التالية، أنشئ محتوى LinkedIn احترافياً:

المطور: ${fullName}
GitHub: ${user.login}
المتابعون: ${user.followers}
المتابَعون: ${user.following}
المستودعات العامة: ${total_repos}
إجمالي النجوم: ${total_stars}
سنوات الخبرة (تقديرياً): ${accountAge}+
اللغات الأساسية: ${topLangs.join(", ")}
النبذة على GitHub: ${user.bio || "غير محددة"}
الموقع: ${user.location || "غير محدد"}
الشركة: ${user.company || "غير محددة"}

أهم المستودعات:
${JSON.stringify(repoSummaries, null, 2)}

إحصائيات للـ Score:
- مستودعات مع وصف: ${reposWithDesc.length} من ${top_repos.length}
- مستودعات مع README: ${reposWithReadme.length} من ${top_repos.length}
- نشاط في آخر 90 يوم: ${recentlyActive.length} مستودع
- تنوع اللغات: ${topLangs.length} لغة

أنشئ هذا الـ JSON فقط (بدون نص إضافي):
{
  "score": <رقم من 0 إلى 100 بناءً على تحليل موضوعي>,
  "score_breakdown": {
    "readme_quality": <0-20: جودة الـ README والتوثيق>,
    "commit_frequency": <0-20: انتظام النشاط والـ commits>,
    "repo_descriptions": <0-20: وصف المستودعات>,
    "project_diversity": <0-20: تنوع المشاريع والتقنيات>,
    "profile_completeness": <0-20: اكتمال الملف الشخصي>
  },
  "weak_points": [
    "<نقطة ضعف محددة مع اقتراح تحسين>",
    "<نقطة ضعف 2>",
    "<نقطة ضعف 3 — اختياري>"
  ],
  "headline": "<عنوان LinkedIn واحد — 120 حرف كحد أقصى — محدد ومؤثر>",
  "about": "<قسم About كامل — 3-5 فقرات — احترافي وجذاب — يبدأ بـ hook قوي>",
  "posts": [
    {
      "repo_name": "<اسم المستودع من القائمة>",
      "post_content": "<منشور LinkedIn جاهز للنشر — 150-300 كلمة — يبدأ بـ hook — يشرح المشكلة والحل والتقنيات — ينتهي بـ CTA>${viralTag}"
    }
  ]
}

قواعد:
- الـ score موضوعي بناءً على الإحصائيات الفعلية أعلاه
- weak_points محددة وقابلة للتنفيذ — لا عموميات
- headline: لا تستخدم "passionate about" أو "love coding"
- posts: لكل مستودع في القائمة منشور واحد بالترتيب
- about: يبدأ بـ hook قوي (إحصائية أو سؤال أو جملة مميزة)`;

  const promptEn = `Based on the following GitHub data, generate professional LinkedIn content:

Developer: ${fullName}
GitHub: ${user.login}
Followers: ${user.followers}
Following: ${user.following}
Public Repos: ${total_repos}
Total Stars: ${total_stars}
Years on GitHub (estimated): ${accountAge}+
Primary Languages: ${topLangs.join(", ")}
GitHub Bio: ${user.bio || "Not provided"}
Location: ${user.location || "Not provided"}
Company: ${user.company || "Not provided"}

Top Repositories:
${JSON.stringify(repoSummaries, null, 2)}

Stats for Score Calculation:
- Repos with description: ${reposWithDesc.length} of ${top_repos.length}
- Repos with README: ${reposWithReadme.length} of ${top_repos.length}
- Active in last 90 days: ${recentlyActive.length} repos
- Language diversity: ${topLangs.length} languages

Generate ONLY this JSON (no extra text):
{
  "score": <number 0-100 based on objective analysis of above stats>,
  "score_breakdown": {
    "readme_quality": <0-20: README quality and documentation>,
    "commit_frequency": <0-20: activity consistency>,
    "repo_descriptions": <0-20: repo description quality>,
    "project_diversity": <0-20: project and tech diversity>,
    "profile_completeness": <0-20: profile completeness>
  },
  "weak_points": [
    "<specific weak point with actionable improvement suggestion>",
    "<weak point 2>",
    "<weak point 3 — optional>"
  ],
  "headline": "<single LinkedIn headline — max 120 chars — specific and impactful>",
  "about": "<full About section — 3-5 paragraphs — professional and compelling — starts with a strong hook>",
  "posts": [
    {
      "repo_name": "<exact repo name from list above>",
      "post_content": "<ready-to-post LinkedIn post — 150-300 words — starts with hook — explains problem/solution/tech — ends with CTA>${viralTag}"
    }
  ]
}

Rules:
- score is objective based on the actual stats provided above
- weak_points must be specific and actionable — no generic advice
- headline: avoid "passionate about" or "love coding" clichés
- posts: one post per repo in the list, in order
- about: start with a strong hook (stat, question, or standout statement)`;

  return {
    system: isArabic ? systemAr : systemEn,
    user: isArabic ? promptAr : promptEn,
  };
}

// ─── Helper: Call Groq API ────────────────────────────────────────────────────

async function callGroqAPI(
  prompt: { system: string; user: string },
  apiKey: string
): Promise<LinkedInResponse & { _tokensUsed: number }> {
  const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";
  const MODEL = "meta-llama/llama-4-scout-17b-16e-instruct";

  const response = await fetch(GROQ_API_URL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: "system", content: prompt.system },
        { role: "user", content: prompt.user },
      ],
      max_tokens: 4000,
      temperature: 0.72,
      top_p: 0.9,
      response_format: { type: "json_object" },
    }),
    signal: AbortSignal.timeout(45_000),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    console.error("[linkedin-generate] Groq error:", response.status, errorBody);
    if (response.status === 429)
      throw new Error("RATE_LIMITED: Groq API rate limit reached. Please try again in a moment.");
    if (response.status === 401)
      throw new Error("AUTH_ERROR: Invalid Groq API key.");
    throw new Error(`GROQ_ERROR: ${response.status} — ${errorBody.slice(0, 200)}`);
  }

  const data = await response.json();
  const content = data?.choices?.[0]?.message?.content;
  if (!content) throw new Error("EMPTY_RESPONSE: Groq returned no content.");

  const tokensUsed = data?.usage?.total_tokens || 0;

  let parsed: LinkedInResponse;
  try {
    parsed = JSON.parse(content);
  } catch {
    const jsonMatch = content.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("PARSE_ERROR: Could not parse AI response as JSON.");
    parsed = JSON.parse(jsonMatch[0]);
  }

  // Validate required fields
  if (
    typeof parsed.score !== "number" ||
    !parsed.score_breakdown ||
    !Array.isArray(parsed.weak_points) ||
    !parsed.headline ||
    !parsed.about ||
    !Array.isArray(parsed.posts)
  ) {
    throw new Error("INVALID_STRUCTURE: AI response missing required fields.");
  }

  // Sanitize & clamp
  return {
    score: Math.min(100, Math.max(0, Math.round(parsed.score))),
    score_breakdown: {
      readme_quality:       Math.min(20, Math.max(0, Math.round(parsed.score_breakdown.readme_quality || 0))),
      commit_frequency:     Math.min(20, Math.max(0, Math.round(parsed.score_breakdown.commit_frequency || 0))),
      repo_descriptions:    Math.min(20, Math.max(0, Math.round(parsed.score_breakdown.repo_descriptions || 0))),
      project_diversity:    Math.min(20, Math.max(0, Math.round(parsed.score_breakdown.project_diversity || 0))),
      profile_completeness: Math.min(20, Math.max(0, Math.round(parsed.score_breakdown.profile_completeness || 0))),
    },
    weak_points: parsed.weak_points.slice(0, 4).map((w: unknown) => String(w).trim()).filter(Boolean),
    headline: String(parsed.headline).trim().slice(0, 220),
    about: String(parsed.about).trim(),
    posts: parsed.posts.map((p: { repo_name?: unknown; post_content?: unknown }) => ({
      repo_name: String(p.repo_name || "").trim(),
      post_content: String(p.post_content || "").trim(),
    })),
    _tokensUsed: tokensUsed,
  };
}

// ─── Main Handler ─────────────────────────────────────────────────────────────

serve(async (req: Request) => {
  const requestOrigin = req.headers.get("origin");
  const corsHeaders = getCorsHeaders(requestOrigin);

  // CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  const supabaseUrl = Deno.env.get("SUPABASE_URL") || "";
  const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
  const groqApiKey = Deno.env.get("GROQ_API_KEY") || "";

  if (!groqApiKey) {
    return new Response(
      JSON.stringify({ error: "Server configuration error." }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  const supabase = createClient(supabaseUrl, supabaseServiceKey);
  let generationId = "";

  try {
    // Parse body
    let body: LinkedInRequest;
    try {
      body = await req.json();
    } catch {
      return new Response(
        JSON.stringify({ error: "Invalid JSON in request body." }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    if (!body.githubData?.user || !body.githubData?.top_repos) {
      return new Response(
        JSON.stringify({ error: "Missing githubData.user or githubData.top_repos" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const lang = body.lang === "ar" ? "ar" : "en";
    generationId = body.generationId || "";

    // Rate Limiting: reuse ai_generations table — max 5/day per user
    const authHeader = req.headers.get("authorization") || "";
    const token = authHeader.replace("Bearer ", "").trim();

    if (token && token !== (Deno.env.get("SUPABASE_ANON_KEY") || "")) {
      try {
        const { data: userPayload } = await supabase.auth.getUser(token);
        const userId = userPayload?.user?.id;

        if (userId) {
          const since24h = new Date(Date.now() - 86_400_000).toISOString();
          const { count } = await supabase
            .from("ai_generations")
            .select("*", { count: "exact", head: true })
            .eq("user_id", userId)
            .gte("created_at", since24h);

          if ((count ?? 0) >= 5) {
            return new Response(
              JSON.stringify({
                success: false,
                error: "RATE_LIMITED: You've reached the daily limit (5 generations/day). Please try again tomorrow.",
                code: "RATE_LIMITED",
              }),
              { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } }
            );
          }
        }
      } catch (rateLimitErr) {
        console.warn("[linkedin-generate] Rate limit check failed:", rateLimitErr);
      }
    }

    await updateGenerationStatus(supabase, generationId, "processing", {
      github_data: body.githubData,
    });

    console.log(`[linkedin-generate] Starting for: ${body.githubData.user.login} | lang: ${lang}`);

    const prompt = buildPrompt({ ...body, lang });
    const result = await callGroqAPI(prompt, groqApiKey);

    const tokensUsed = result._tokensUsed;
    // @ts-ignore
    delete result._tokensUsed;

    console.log(`[linkedin-generate] Done for ${body.githubData.user.login} — ${tokensUsed} tokens`);

    await updateGenerationStatus(supabase, generationId, "completed", {
      tokens_used: tokensUsed,
    });

    return new Response(JSON.stringify({ success: true, data: result }), {
      status: 200,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("[linkedin-generate] Error:", errorMessage);

    await updateGenerationStatus(supabase, generationId, "failed", {
      error_message: errorMessage.slice(0, 500),
    });

    let statusCode = 500;
    if (errorMessage.startsWith("RATE_LIMITED")) statusCode = 429;
    if (errorMessage.startsWith("AUTH_ERROR")) statusCode = 401;
    if (errorMessage.startsWith("PARSE_ERROR") || errorMessage.startsWith("INVALID_STRUCTURE"))
      statusCode = 422;

    return new Response(
      JSON.stringify({
        success: false,
        error: errorMessage,
        code: errorMessage.split(":")[0],
      }),
      { status: statusCode, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
